### ISSUE TITLE
In hero Section there is some unaligned texts

### ISSUE THREAD

**Issue by TheAshutoshGupta** [premvarma2002/nextjs-shadcn.ui-portfolio#1]
![Screenshot 2024-05-17 231722](https://github.com/premvarma2002/nextjs-shadcn.ui-portfolio/assets/125827121/2312a9d8-a35c-464a-bb5d-009d24fd198a)

**Comment by premvarma2002** [comment]
Yes , it was a alignment issue there and i fixed it . now it fixes #1

![image](https://github.com/premvarma2002/nextjs-shadcn.ui-portfolio/assets/98645019/8dc513ef-5afe-4fb3-a023-bdf600290b06)
